### ISSUE TITLE
Doesn't Work in LeveledMobs Minecraft Version 1.16.1.

### ISSUE THREAD

**Issue by melihcan564** [lokka30/LevelledMobs#100]
I have installed the LeveledMobs versions 1.34,1.33.9,1.33.8 one by one and when I put it on the server it gives me an error from the panel.

[22:52:43 WARN]: org.bukkit.plugin.InvalidPluginException: java.io.FileNotFoundException: plugins\levelled.jar does not exist
[22:52:43 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:77)
[22:52:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397)
[22:52:43 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[22:52:43 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[22:52:43 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[22:52:43 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:52:43 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[22:52:43 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005)
[22:52:43 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[22:52:43 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:52:43 WARN]: Caused by: java.io.FileNotFoundException: plugins\levelled.jar does not exist
[22:52:43 WARN]:        ... 24 more

**Comment by lokka30** [comment]
Using a plugin manager is not recommended by many experts in the Spigot community. First time I've ever heard of this issue, and I am 99% sure that it is directly caused by PlugMan, or the way you are using PlugMan.

Please read the Installation page on the Wiki! You wouldn't have encountered this issue if you installed LevelledMobs the way every other plugin should be installed :)

Also, please be aware that all of my resources are currently not being updated or supported. Since this is just a simple issue, I thought I'd help you out anyways. Here's what I put on the top of the LevelledMobs resource post on SpigotMC:

> Important Notice - 29 August 2020
> This resource has been discontinued. Support and updates to the resource will therefore not be provided.
> For more information, see the announcement on my Discord server.
