### ISSUE TITLE
Bug: Console Error

### ISSUE THREAD

**Issue by Asttear** [lokka30/LevelledMobs#220]
**Steps to Reproduce**
1. It occurs when a player dies

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/16262778/116368381-dc265000-a83a-11eb-8ee8-a682cf6f702a.png)

**Server software**
Paper

**Server version**
Minecraft 1.16.5

**LevelledMobs version**
2.5.0 b372

**Config files, if applicable**
https://paste.gg/p/anonymous/576b3adb3ba941d19f7031c326c39892

**Additional context**
[15:38:55 ERROR]: Could not pass event PlayerDeathEvent to LevelledMobs v2.5.0 b372
java.lang.NullPointerException: null
        at me.lokka30.levelledmobs.misc.Utils.replaceEx(Utils.java:69) ~[?:?]
        at me.lokka30.levelledmobs.listeners.EntitySpawnListener.onPlayerDeath(EntitySpawnListener.java:66) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor296.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-610]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-610]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-610]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-610]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:855) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:808) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:858) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:972) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityInsentient.attackEntity(EntityInsentient.java:1591) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityZombie.attackEntity(EntityZombie.java:363) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.a(SourceFile:142) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.PathfinderGoalZombieAttack.e(SourceFile:28) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:150) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityInsentient.doTick(EntityInsentient.java:829) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityLiving.movementTick(EntityLiving.java:2865) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityInsentient.movementTick(EntityInsentient.java:615) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityMonster.movementTick(EntityMonster.java:45) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityZombie.movementTick(EntityZombie.java:267) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2591) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:378) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.EntityZombie.tick(EntityZombie.java:237) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.World.a(World.java:946) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1486) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-610]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-610]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by lokka30** [comment]
Hi, I have just inspected the code and I believe I have found an issue: the *death* nametag specifically doesn't actually allow `disabled`, even though it intends to. I have added this functionality to the code now.

I have just commited the code for `2.6.1 b385`, once it is tested and validated then we can release it. :)

**Comment by lokka30** [comment]
Oops, I did not mean to close the issue. I apologise.

**Comment by Asttear** [comment]
I've tested it on my server and it seemed to work fine. Thanks for your work!
