### ISSUE TITLE
NPE when updating nametags

### ISSUE THREAD

**Issue by lokka30** [lokka30/LevelledMobs#309]
```
[10:44:33] [Craft Scheduler Thread - 98 - LevelledMobs/WARN]: [LevelledMobs] Plugin LevelledMobs v3.2.1 b536 generated an exception while executing task 126223
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getType()" because "this.livingEntity" is null
    at me.lokka30.levelledmobs.misc.LivingEntityWrapper.getTypeName(LivingEntityWrapper.java:253) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.misc.LivingEntityWrapper.buildApplicableGroupsForMob(LivingEntityWrapper.java:501) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.misc.LivingEntityWrapper.getApplicableGroups(LivingEntityWrapper.java:259) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.misc.CachedModalList.isEnabledInList(CachedModalList.java:53) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.rules.RulesManager.isRuleApplicable_Entity(RulesManager.java:564) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.rules.RulesManager.getApplicableRules(RulesManager.java:506) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.misc.LivingEntityWrapper.buildCache(LivingEntityWrapper.java:167) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.misc.LivingEntityWrapper.getApplicableRules(LivingEntityWrapper.java:295) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.rules.RulesManager.getRule_CreatureNametagVisbility(RulesManager.java:360) ~[LevelledMobs-3.2.1 b536.jar:?]
    at me.lokka30.levelledmobs.managers.LevelManager.runNametagCheck_aSync(LevelManager.java:687) ~[LevelledMobs-3.2.1 b536.jar:?]
~snip~
```

https://discord.com/channels/752310043214479462/760051505067458590/898812178646302730

**Comment by stumper66** [comment]
This has been resolved in the latest 3.2.x release versions
