### ISSUE TITLE
PDC concurrent modification exception

### ISSUE THREAD

**Issue by Grafhugo** [lokka30/LevelledMobs#350]
**Describe the bug**
I'm getting this in my console

```
[09:31:23 WARN]: [LevelledMobs] Plugin LevelledMobs v3.3.2 b596 generated an exception while executing task 2163
java.util.ConcurrentModificationException: null
        at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.persistence.CraftPersistentDataTypeRegistry.isInstanceOf(CraftPersistentDataTypeRegistry.java:231) ~[paper-1.18.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_18_R1.persistence.CraftPersistentDataContainer.has(CraftPersistentDataContainer.java:54) ~[paper-1.18.1.jar:git-Paper-117]
        at me.lokka30.levelledmobs.misc.LivingEntityWrapper.getSpawnReason(LivingEntityWrapper.java:433) ~[LevelledMobs-3.3.2 b596.jar:?]
        at me.lokka30.levelledmobs.rules.RulesManager.isRuleApplicable_Entity(RulesManager.java:559) ~[LevelledMobs-3.3.2 b596.jar:?]
        at me.lokka30.levelledmobs.rules.RulesManager.getApplicableRules(RulesManager.java:501) ~[LevelledMobs-3.3.2 b596.jar:?]
        at me.lokka30.levelledmobs.misc.LivingEntityWrapper.buildCache(LivingEntityWrapper.java:200) ~[LevelledMobs-3.3.2 b596.jar:?]
        at me.lokka30.levelledmobs.misc.LivingEntityWrapper.getApplicableRules(LivingEntityWrapper.java:382) ~[LevelledMobs-3.3.2 b596.jar:?]
        at me.lokka30.levelledmobs.rules.RulesManager.getRule_Nametag(RulesManager.java:298) ~[LevelledMobs-3.3.2 b596.jar:?]
        at me.lokka30.levelledmobs.managers.LevelManager.getNametag(LevelManager.java:537) ~[LevelledMobs-3.3.2 b596.jar:?]
        at me.lokka30.levelledmobs.listeners.PlayerJoinListener.updateNametagsInWorld(PlayerJoinListener.java:147) ~[LevelledMobs-3.3.2 b596.jar:?]
        at me.lokka30.levelledmobs.listeners.PlayerJoinListener$1.run(PlayerJoinListener.java:122) ~[LevelledMobs-3.3.2 b596.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-117]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-117]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Server software**
paper

**Server version**
1.18.1

**LevelledMobs version**
3.3.2 b596

**Comment by lokka30** [comment]
Thanks for reporting this bug :)

**Comment by stumper66** [comment]
@Grafhugo this is fixed in LevelledMobs v3.3.3 b600.  You can find the build on the ArcanePlugin's Discord under #dev-builds

**Comment by lokka30** [comment]
@Grafhugo did the dev build fix it?

**Comment by Grafhugo** [comment]
sorry for not writing!

I did not find any more errors
