### ISSUE TITLE
Console spam of NullPointerException

### ISSUE THREAD

**Issue by masterdesky** [lokka30/LevelledMobs#351]
**Describe the bug**
Console is spammed with the same error message (probably for every mob near the player). The following is an example:

```
[16:28:03 INFO]: [ERROR] LevelledMobs: Got exception while processing nametag updates on SKELETON
[16:28:03 WARN]: java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.reflect.accessors.MethodAccessor.invoke(Object, Object[])" because "com.comphenix.protocol.wrappers.WrappedDataWatcher.SETTER" is null
[16:28:03 WARN]: at ProtocolLib.jar//com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:510)
[16:28:03 WARN]: at ProtocolLib.jar//com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:525)
[16:28:03 WARN]: at LevelledMobs-3.3.2 b596.jar//me.lokka30.levelledmobs.managers.NametagQueueManager.updateNametag(NametagQueueManager.java:214)
[16:28:03 WARN]: at LevelledMobs-3.3.2 b596.jar//me.lokka30.levelledmobs.managers.NametagQueueManager.processItem(NametagQueueManager.java:167)
[16:28:03 WARN]: at LevelledMobs-3.3.2 b596.jar//me.lokka30.levelledmobs.managers.NametagQueueManager.main(NametagQueueManager.java:103)
[16:28:03 WARN]: at LevelledMobs-3.3.2 b596.jar//me.lokka30.levelledmobs.managers.NametagQueueManager$1.run(NametagQueueManager.java:65)
[16:28:03 WARN]: at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:28:03 WARN]: at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:28:03 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:28:03 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:28:03 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:28:03 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
```

**Steps to Reproduce**
I wanted to try LevelledMobs for the first time, first only with the default settings **on an existing world**, but was spammed with this error message in console immediately after joining the server. I even traveled far away to find newly generated mobs, but it did not helped.

**Server software**
Newest Paper build - git-Paper-133 (MC: 1.18.1)

**Server version**
1.18.1

**LevelledMobs version**
3.3.2 b596

**Config files, if applicable**
Default, out-of-the-box settings.

**Comment by stumper66** [comment]
You need to install the latest dev build of ProtocolLib https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
This is written everywhere; on ProtocolLib's spigotmc page, on LevelledMobs spigot page.
