### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Grafhugo** [lokka30/LevelledMobs#352]
Hey i just start my 1.18.1 Paper MC server and im recieving this error:

[11:48:09 INFO]: [ERROR] LevelledMobs: Got exception while processing nametag updates on CREEPER
[11:48:09 WARN]: java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.reflect.accessors.MethodAccessor.invoke(Object, Object[])" because "com.comphenix.protocol.wrappers.WrappedDataWatcher.SETTER" is null
[11:48:09 WARN]:        at ProtocolLib (15).jar//com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:510)
[11:48:09 WARN]:        at ProtocolLib (15).jar//com.comphenix.protocol.wrappers.WrappedDataWatcher.setObject(WrappedDataWatcher.java:525)
[11:48:09 WARN]:        at LevelledMobs-3.3.2 b596 (2).jar//me.lokka30.levelledmobs.managers.NametagQueueManager.updateNametag(NametagQueueManager.java:214)
[11:48:09 WARN]:        at LevelledMobs-3.3.2 b596 (2).jar//me.lokka30.levelledmobs.managers.NametagQueueManager.processItem(NametagQueueManager.java:167)
[11:48:09 WARN]:        at LevelledMobs-3.3.2 b596 (2).jar//me.lokka30.levelledmobs.managers.NametagQueueManager.main(NametagQueueManager.java:103)
[11:48:09 WARN]:        at LevelledMobs-3.3.2 b596 (2).jar//me.lokka30.levelledmobs.managers.NametagQueueManager$1.run(NametagQueueManager.java:65)
[11:48:09 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[11:48:09 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:48:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:48:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:48:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:48:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by UltimaOath** [comment]
Make sure you have the latest DEVELOPER build, not the latest release, of
ProtocolLib.
