### ISSUE TITLE
Error at start up

### ISSUE THREAD

**Issue by SharasGit** [lokka30/LevelledMobs#59]
Hello. Just installed LevelledMobs and my console give me this error everytime server start : 

[22:41:45] [Server thread/INFO]: [LevelledMobs] Loading LevelledMobs v1.30.0-RELEASE
[22:41:45] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_15_R1.CraftServer] com/sk89q/worldguard/protection/flags/Flag initializing LevelledMobs v1.30.0-RELEASE (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
	at io.github.lokka30.levelledmobs.LevelledMobs.onLoad(LevelledMobs.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:363) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-211]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-211]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-211]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
	... 5 more

You can see my full starting/closing log attached. Thank you !
[latest.log](https://github.com/lokka30/LevelledMobs/files/4525184/latest.log)

**Comment by lokka30** [comment]
Hi, thanks for reporting the issue.

- Do you have WorldGuard installed?

- Are you using the latest recommended WorldGuard version from the Bukkit site? Not a snapshot version?

**Comment by SharasGit** [comment]
Hello,
No, i don't use WorldGuard. Only the last version of WorldEdit.
I tried to remove WorldEdit, but still have this error showing.
Thank you.

**Comment by lokka30** [comment]
Okay, I will take a look now

**Comment by lokka30** [comment]
I have a jar file which might fix the problem, could I send it to you over Discord?

**Comment by SharasGit** [comment]
Sure. You can contact me at : Sharas#4811

**Comment by lokka30** [comment]
Added. :)

**Comment by lokka30** [comment]
Resolved in upcoming release
