### ISSUE TITLE
Error on 1.16

### ISSUE THREAD

**Issue by GameD101** [lokka30/LevelledMobs#90]
This message keeps popping up on the console.
Please help.
`[19:50:27] [Server thread/WARN]: [LevelledMobs] Task #3072 for LevelledMobs v1.33.9-RELEASE generated an exception
java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_141]
at io.github.lokka30.levelledmobs.utils.LevelManager.setTag(LevelManager.java:85) ~[?:?]
at io.github.lokka30.levelledmobs.utils.LevelManager$1.run(LevelManager.java:63) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-758abbe-2b00831]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:git-Spigot-758abbe-2b00831]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1059) ~[server.jar:git-Spigot-758abbe-2b00831]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[server.jar:git-Spigot-758abbe-2b00831]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1007) ~[server.jar:git-Spigot-758abbe-2b00831]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:846) ~[server.jar:git-Spigot-758abbe-2b00831]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-758abbe-2b00831]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]`

**Comment by lokka30** [comment]
Please send me your `settings.yml` file over Hastebin and also ensure that your SpigotMC software is running the latest release from BuildTools.

**Comment by murz1koffski** [comment]
I have the same problem. 1.16.1

**Comment by murz1koffski** [comment]
and, I don't know if the plugin works. I don't see a table where it should be. commands are working.

**Comment by murz1koffski** [comment]
> Please send me your `settings.yml` file over Hastebin and also ensure that your SpigotMC software is running the latest release from BuildTools.

this is standar settings, I have this problem too, I haven't changed anything.

**Comment by murz1koffski** [comment]
> > Please send me your `settings.yml` file over Hastebin and also ensure that your SpigotMC software is running the latest release from BuildTools.
> 
> this is standar settings, I have this problem too, I haven't changed anything.

and when I changed "enable-nametag-changes: true" to false, it stopped writing to the console, but the plugin doesn't work either.

**Comment by lokka30** [comment]
Try this:
1. Delete your current spigot.jar file in your server
2. Run build tools again
3. Put the new jar into your server
4. Start it up and see if the issue is gone

**Comment by murz1koffski** [comment]
build tools? im using hosting.

**Comment by lokka30** [comment]
The issue is directly related to the server running an outdated version of the server software. The issue is not to do with my software.

**Comment by lokka30** [comment]
If your host or you are unable to update the software then there is nothing that can be done about the issue.

**Comment by murz1koffski** [comment]
thx
